spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/metroCard"
    username: "postgres"
    password: "postgres"
  flyway:
#    enabled: true
#    validate-on-migrate: true