spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/metrocard"
    username: "postgres"
    password: "postgres"
  flyway:
    enabled: false
#    validate-on-migrate: true
server:
  error:
    include-stacktrace: never
